<?php

return array(
    'name' => '用户',
    'pid' => '0',
    'type' => 1,
    'icon' => 'user',
    'child' => array(
        array(
            'name' => '用户管理',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'Index',
            'lev3' => 'index',
            'sort' => 1,
            'icon' => 'icon-addressbook_fill',
        ),
        array(
            'name' => '等级管理',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'AdminRank',
            'lev3' => 'index',
            'sort' => 2,
            'icon' => 'icon-collection_fill',
        ),
        array(
            'name' => '站内信',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'AdminMsg',
            'lev3' => 'index',
            'sort' => 2,
            'icon' => 'icon-interactive_fill',
        ),
        array(
            'name' => '提现申请',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'UserCashoutApply',
            'lev3' => 'index',
            'sort' => 3,
            'icon' => 'icon-financial_fill',
        ),
        array(
            'name' => '提现渠道',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'UserCashoutChannel',
            'lev3' => 'index',
            'sort' => 3,
            'icon' => 'icon-financial_fill',
        ),
        array(
            'name' => '积分日志',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'AdminLog',
            'lev3' => 'dot',
            'sort' => 4,
            'icon' => 'icon-createtask_fill',
        ),
        array(
            'name' => '佣金日志',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'AdminLog',
            'lev3' => 'bro',
            'sort' => 5,
            'icon' => 'icon-barrage_fill',
        ),
        array(
            'name' => '余额日志',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'AdminLog',
            'lev3' => 'money',
            'sort' => 6,
            'icon' => 'icon-activity_fill',
        ),
        array(
            'name' => '登陆日志',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'AdminLog',
            'lev3' => 'login',
            'sort' => 6,
            'icon' => 'icon-barrage_fill',
        ),
        array(
            'name' => '地址管理',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'AdminAddress',
            'lev3' => 'index',
            'sort' => 7,
            'icon' => 'icon-shielding_fill',
        ),
        array(
            'name' => '设置上级',
            'type' => 1,
            'lev1' => 'user',
            'lev2' => 'Index',
            'lev3' => 'set_pid',
            'sort' => 7,
            'icon' => 'icon-marketing_fill',
        ),
    )
);
