<?php

return array(
    'mall_an' => array('mall_an', '不存在', '不存在', 'success'),
    'mall_bro_rule' => array('mall_bro_rule', '不存在', '不存在', 'success'),
    'mall_coupon' => array('mall_coupon', '不存在', '不存在', 'success'),
    'mall_express_company' => array('mall_express_company', '不存在', '不存在', 'success'),
    'mall_get_coupon' => array('mall_get_coupon', '不存在', '不存在', 'success'),
    'mall_goods' => array('mall_goods', '不存在', '不存在', 'success'),
    'mall_goods_atn' => array('mall_goods_atn', '不存在', '不存在', 'success'),
    'mall_goods_attr' => array('mall_goods_attr', '不存在', '不存在', 'success'),
    'mall_goods_attr_field' => array('mall_goods_attr_field', '不存在', '不存在', 'success'),
    'mall_goods_attr_record' => array('mall_goods_attr_record', '不存在', '不存在', 'success'),
    'mall_goods_brand' => array('mall_goods_brand', '不存在', '不存在', 'success'),
    'mall_goods_brand_relation' => array('mall_goods_brand_relation', '不存在', '不存在', 'success'),
    'mall_goods_category' => array('mall_goods_category', '不存在', '不存在', 'success'),
    'mall_goods_category_relation' => array('mall_goods_category_relation', '不存在', '不存在', 'success'),
    'mall_goods_comment' => array('mall_goods_comment', '不存在', '不存在', 'success'),
    'mall_goods_data' => array('mall_goods_data', '不存在', '不存在', 'success'),
    'mall_goods_ext' => array('mall_goods_ext', '不存在', '不存在', 'success'),
    'mall_goods_field_relation' => array('mall_goods_field_relation', '不存在', '不存在', 'success'),
    'mall_goods_spec' => array('mall_goods_spec', '不存在', '不存在', 'success'),
    'mall_order' => array('mall_order', '不存在', '不存在', 'success'),
    'mall_order_bro' => array('mall_order_bro', '不存在', '不存在', 'success'),
    'mall_order_feedback' => array('mall_order_feedback', '不存在', '不存在', 'success'),
    'mall_order_goods' => array('mall_order_goods', '不存在', '不存在', 'success'),
    'mall_order_log' => array('mall_order_log', '不存在', '不存在', 'success'),
    'mall_order_send' => array('mall_order_send', '不存在', '不存在', 'success'),
);
