<?php

return [
    'table' => [
        // '表名' => 是否打包数据
        'category' => 0,
        'category_extend' => 0,
        'category_theme' => 0,
        'content' => 0,
        'system_field' => 0,
        'system_model' => 0
    ],
    //先使用shell.show_file 方法就可以列出文件列表啦
    'file' => [
        '../app/admin/Data/HTML/add_ad.php',
        '../app/admin/Data/HTML/checkbox.php',
        '../app/admin/Data/HTML/date.php',
        '../app/admin/Data/HTML/datetime.php',
        '../app/admin/Data/HTML/editor.php',
        '../app/admin/Data/HTML/file.php',
        '../app/admin/Data/HTML/files.php',
        '../app/admin/Data/HTML/images.php',
        '../app/admin/Data/HTML/input.php',
        '../app/admin/Data/HTML/radio.php',
        '../app/admin/Data/HTML/select.php',
        '../app/admin/Data/HTML/textarea.php',
        '../app/admin/Data/HTML/thumb.php',
        '../app/admin/Data/HTML/time.php',
        '../app/admin/Data/SQL/add_field.php',
        '../app/admin/Data/SQL/alter_field.php',
        '../app/admin/Data/SQL/cretae_model_table.php',
        '../app/admin/Data/SQL/delete_table.php',
        '../app/admin/Data/SQL/drop_field.php',
        '../app/admin/Data/SQL/insert_field.php',
        '../app/admin/controller/Category.php',
        '../app/admin/controller/Content.php',
        '../app/admin/controller/Field.php',
        '../app/admin/controller/Model.php',
        '../app/admin/model/Category.php',
        '../app/admin/model/Content.php',
        '../app/admin/model/Field.php',
        '../app/admin/model/ModelM.php',
        '../app/admin/view/category/category_list.php',
        '../app/admin/view/category/category_show.php',
        '../app/admin/view/category/category_show_js.php',
        '../app/admin/view/category/set_field.php',
        '../app/admin/view/category/theme_index.php',
        '../app/admin/view/category/top.php',
        '../app/admin/view/content/content_list.php',
        '../app/admin/view/content/content_page.php',
        '../app/admin/view/content/content_show.php',
        '../app/admin/view/content/top.php',
        '../app/admin/view/field/field_list.php',
        '../app/admin/view/field/field_show.php',
        '../app/admin/view/field/top.php',
        '../app/admin/view/model/copy.php',
        '../app/admin/view/model/index.php',
        '../app/admin/view/model/model_show.php',
        '../app/admin/view/model/top.php',
        '../app/home/controller/Content.php',
        '../app/home/controller/Error.php',
        '../app/home/model/Category.php',
        '../app/home/model/Content.php',
//                    '../com_install.sql',
    ],];
